services:
  db:
    image: postgres:18
    container_name: thebigsorter-db
    restart: always
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: TheBigSorter
    volumes:
      - TheBigSorter:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  TheBigSorter:
